name: build

on:
  workflow_run:
    types: [completed]
    branches: [master]
    workflows: [lint-typecheck]

jobs:
  fail:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
    - name: Fail deployment
      uses: actions/github-script@v3
      with:
        script: core.setFailed("Cannot deploy as lint-typecheck failed")

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the docs
      run: |
        npm ci
        npm run build

    - name: Deploy to Public branch
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: public
        folder: .vitepress/dist
